# Setup
title:        SparkQML
tagline:      Interactive QML File Viewer for Transition Preview
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Ben Lau
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown